Repository Azure/review-checklists, pull requests merged in 2024-09, with the labels that each got.

#863 Latest version of the WAF service guides retrieved
  checklists-ext/appservicewebapps_sg_checklist.en.json
  checklists-ext/azureapplicationgateway_sg_checklist.en.json
  checklists-ext/azureblobstorage_sg_checklist.en.json
  checklists-ext/azureexpressroute_sg_checklist.en.json
  checklists-ext/azurefiles_sg_checklist.en.json
  checklists-ext/azurefirewall_sg_checklist.en.json
  checklists-ext/azurefrontdoor_sg_checklist.en.json
  checklists-ext/azurekubernetesservice_sg_checklist.en.json
  checklists-ext/azuremachinelearning_sg_checklist.en.json
  checklists-ext/azureopenai_sg_checklist.en.json
  checklists-ext/virtualmachines_sg_checklist.en.json
  checklists-ext/wafsg_checklist.en.json
Labels: automated

#868 Latest version of the WAF service guides retrieved
  checklists-ext/appservicewebapps_sg_checklist.en.json
  checklists-ext/azureapplicationgateway_sg_checklist.en.json
  checklists-ext/azureblobstorage_sg_checklist.en.json
  checklists-ext/azureexpressroute_sg_checklist.en.json
  checklists-ext/azurefiles_sg_checklist.en.json
  checklists-ext/azurefirewall_sg_checklist.en.json
  checklists-ext/azurefrontdoor_sg_checklist.en.json
  checklists-ext/azurekubernetesservice_sg_checklist.en.json
  checklists-ext/azuremachinelearning_sg_checklist.en.json
  checklists-ext/azureopenai_sg_checklist.en.json
  checklists-ext/virtualmachines_sg_checklist.en.json
  checklists-ext/wafsg_checklist.en.json
Labels: automated

#859 Adding resiliency checks for alz services
  checklists/alz_checklist.en.json
Labels: landingzone

#828 Update alz_checklist.en.json (Governance Training Links)
  checklists/alz_checklist.en.json
Labels: landingzone

#874 Latest version of the WAF service guides retrieved
  checklists-ext/appservicewebapps_sg_checklist.en.json
  checklists-ext/azureapplicationgateway_sg_checklist.en.json
  checklists-ext/azureblobstorage_sg_checklist.en.json
  checklists-ext/azureexpressroute_sg_checklist.en.json
  checklists-ext/azurefiles_sg_checklist.en.json
  checklists-ext/azurefirewall_sg_checklist.en.json
  checklists-ext/azurefrontdoor_sg_checklist.en.json
  checklists-ext/azurekubernetesservice_sg_checklist.en.json
  checklists-ext/azuremachinelearning_sg_checklist.en.json
  checklists-ext/azureopenai_sg_checklist.en.json
  checklists-ext/virtualmachines_sg_checklist.en.json
  checklists-ext/wafsg_checklist.en.json
Labels: automated

#875 Automatic translation of checklists/servicebus_checklist.en.json
  checklists-ext/fullwaf_checklist.en.json
  checklists/checklist.en.master.json
  checklists/servicebus_checklist.en.json
  checklists/servicebus_checklist.es.json
  checklists/servicebus_checklist.ja.json
  checklists/servicebus_checklist.ko.json
  checklists/servicebus_checklist.pt.json
  checklists/servicebus_checklist.zh-Hant.json
  checklists/waf_checklist.en.json
  checklists/waf_checklist.es.json
  checklists/waf_checklist.ja.json
  checklists/waf_checklist.ko.json
  checklists/waf_checklist.pt.json
  checklists/waf_checklist.zh-Hant.json
  spreadsheet/macrofree/checklist.en.master.xlsx
  spreadsheet/macrofree/servicebus_checklist.en.xlsx
  spreadsheet/macrofree/servicebus_checklist.es.xlsx
  spreadsheet/macrofree/servicebus_checklist.ja.xlsx
  spreadsheet/macrofree/servicebus_checklist.ko.xlsx
  spreadsheet/macrofree/servicebus_checklist.pt.xlsx
  spreadsheet/macrofree/servicebus_checklist.zh-Hant.xlsx
  spreadsheet/macrofree/waf_checklist.en.xlsx
  spreadsheet/macrofree/waf_checklist.es.xlsx
  spreadsheet/macrofree/waf_checklist.ja.xlsx
  spreadsheet/macrofree/waf_checklist.ko.xlsx
  spreadsheet/macrofree/waf_checklist.pt.xlsx
  spreadsheet/macrofree/waf_checklist.zh-Hant.xlsx
  workbooks/alz_checklist.en_network_counters.json
  workbooks/alz_checklist.en_network_counters_template.json
  workbooks/alz_checklist.en_network_tabcounters.json
  workbooks/alz_checklist.en_network_tabcounters_template.json
  workbooks/alz_checklist.en_network_workbook.json
  workbooks/alz_checklist.en_network_workbook_template.json
  workbooks/appdelivery_checklist.en_network_counters_workbook.json
  workbooks/appdelivery_checklist.en_network_counters_workbook_template.json
  workbooks/appdelivery_checklist.en_network_workbook.json
  workbooks/appdelivery_checklist.en_network_workbook_template.json
Labels: automated

#877 Added ARG query for D10.06 in alz_checklist.en.json
  checklists/alz_checklist.en.json
Labels: hackathon

#878 Added ARG query for D10.07 in alz_checklist.en.json
  checklists/alz_checklist.en.json
Labels: hackathon

#894 Automatic translation of checklists/alz_checklist.en.json
  checklists-ext/fullwaf_checklist.en.json
  checklists/alz_checklist.en.json
  checklists/alz_checklist.es.json
  checklists/alz_checklist.ja.json
  checklists/alz_checklist.ko.json
  checklists/alz_checklist.pt.json
  checklists/alz_checklist.zh-Hant.json
  checklists/checklist.en.master.json
  checklists/waf_checklist.en.json
  checklists/waf_checklist.es.json
  checklists/waf_checklist.ja.json
  checklists/waf_checklist.ko.json
  checklists/waf_checklist.pt.json
  checklists/waf_checklist.zh-Hant.json
  spreadsheet/macrofree/alz_checklist.en.xlsx
  spreadsheet/macrofree/alz_checklist.es.xlsx
  spreadsheet/macrofree/alz_checklist.ja.xlsx
  spreadsheet/macrofree/alz_checklist.ko.xlsx
  spreadsheet/macrofree/alz_checklist.pt.xlsx
  spreadsheet/macrofree/alz_checklist.zh-Hant.xlsx
  spreadsheet/macrofree/checklist.en.master.xlsx
  spreadsheet/macrofree/waf_checklist.en.xlsx
  spreadsheet/macrofree/waf_checklist.es.xlsx
  spreadsheet/macrofree/waf_checklist.ja.xlsx
  spreadsheet/macrofree/waf_checklist.ko.xlsx
  spreadsheet/macrofree/waf_checklist.pt.xlsx
  spreadsheet/macrofree/waf_checklist.zh-Hant.xlsx
  workbooks/alz_checklist.en_counters_workbook.json
  workbooks/alz_checklist.en_counters_workbook_template.json
  workbooks/alz_checklist.en_network_counters.json
  workbooks/alz_checklist.en_network_counters_template.json
  workbooks/alz_checklist.en_network_tabcounters.json
  workbooks/alz_checklist.en_network_tabcounters_template.json
  workbooks/alz_checklist.en_network_workbook.json
  workbooks/alz_checklist.en_network_workbook_template.json
  workbooks/alz_checklist.en_workbook.json
  workbooks/alz_checklist.en_workbook_template.json
  workbooks/appdelivery_checklist.en_network_counters_workbook.json
  workbooks/appdelivery_checklist.en_network_counters_workbook_template.json
  workbooks/appdelivery_checklist.en_network_workbook.json
  workbooks/appdelivery_checklist.en_network_workbook_template.json
Labels: automated

#871 Update alz_checklist.en.json
  checklists/alz_checklist.en.json
Labels: landingzone

#916 Latest version of the WAF service guides retrieved
  checklists-ext/appservicewebapps_sg_checklist.en.json
  checklists-ext/azureapplicationgateway_sg_checklist.en.json
  checklists-ext/azureblobstorage_sg_checklist.en.json
  checklists-ext/azureexpressroute_sg_checklist.en.json
  checklists-ext/azurefiles_sg_checklist.en.json
  checklists-ext/azurefirewall_sg_checklist.en.json
  checklists-ext/azurefrontdoor_sg_checklist.en.json
  checklists-ext/azurekubernetesservice_sg_checklist.en.json
  checklists-ext/azuremachinelearning_sg_checklist.en.json
  checklists-ext/azureopenai_sg_checklist.en.json
  checklists-ext/virtualmachines_sg_checklist.en.json
  checklists-ext/wafsg_checklist.en.json
Labels: automated

#913 added kv recommendation and arg query 05.01
  checklists/keyvault_checklist.en.json
Labels: hackathon

#917 Automatic translation of checklists/keyvault_checklist.en.json
  checklists-ext/fullwaf_checklist.en.json
  checklists/checklist.en.master.json
  checklists/keyvault_checklist.en.json
  checklists/keyvault_checklist.es.json
  checklists/keyvault_checklist.ja.json
  checklists/keyvault_checklist.ko.json
  checklists/keyvault_checklist.pt.json
  checklists/keyvault_checklist.zh-Hant.json
  checklists/waf_checklist.en.json
  checklists/waf_checklist.es.json
  checklists/waf_checklist.ja.json
  checklists/waf_checklist.ko.json
  checklists/waf_checklist.pt.json
  checklists/waf_checklist.zh-Hant.json
  spreadsheet/macrofree/checklist.en.master.xlsx
  spreadsheet/macrofree/keyvault_checklist.en.xlsx
  spreadsheet/macrofree/keyvault_checklist.es.xlsx
  spreadsheet/macrofree/keyvault_checklist.ja.xlsx
  spreadsheet/macrofree/keyvault_checklist.ko.xlsx
  spreadsheet/macrofree/keyvault_checklist.pt.xlsx
  spreadsheet/macrofree/keyvault_checklist.zh-Hant.xlsx
  spreadsheet/macrofree/waf_checklist.en.xlsx
  spreadsheet/macrofree/waf_checklist.es.xlsx
  spreadsheet/macrofree/waf_checklist.ja.xlsx
  spreadsheet/macrofree/waf_checklist.ko.xlsx
  spreadsheet/macrofree/waf_checklist.pt.xlsx
  spreadsheet/macrofree/waf_checklist.zh-Hant.xlsx
  workbooks/alz_checklist.en_network_counters.json
  workbooks/alz_checklist.en_network_counters_template.json
  workbooks/alz_checklist.en_network_tabcounters.json
  workbooks/alz_checklist.en_network_tabcounters_template.json
  workbooks/alz_checklist.en_network_workbook.json
  workbooks/alz_checklist.en_network_workbook_template.json
  workbooks/appdelivery_checklist.en_network_counters_workbook.json
  workbooks/appdelivery_checklist.en_network_counters_workbook_template.json
  workbooks/appdelivery_checklist.en_network_workbook.json
  workbooks/appdelivery_checklist.en_network_workbook_template.json
  workbooks/keyvault_checklist.en_counters_workbook.json
  workbooks/keyvault_checklist.en_counters_workbook_template.json
  workbooks/keyvault_checklist.en_workbook.json
  workbooks/keyvault_checklist.en_workbook_template.json
Labels: automated

#912 Add ARG query for D09.04/D09.06 in alz_checklist.en.json
  checklists/alz_checklist.en.json
Labels: hackathon

#911 Added ARG query for C02.05/D01.02/D01.03/D01.04 in avs_checklist.en.json
  checklists/avs_checklist.en.json
Labels: hackathon

#909 Update azfun_checklist.en.json - A01.02 & A01.05
  checklists/azfun_checklist.en.json
Labels: hackathon

#906 Added Storage ARG queries
  checklists/azure_storage_checklist.en.json
Labels: hackathon

#903 Added servicefabric_checklist.en.json - Item ID: C01.01, C01.02, C01.03, C01.04, C01.05, C01.06, C01.07, C01.08
  checklists/servicefabric_checklist.en.json
Labels: hackathon

#886 Added servicefabric_checklist.en.json - Item ID: A01.01, A01.02, A01.03, A01.04, A01.05
  checklists/servicefabric_checklist.en.json
Labels: hackathon

#899 Added servicefabric_checklist.en.json - Item ID: B01.01, B01.02, B01.03
  checklists/servicefabric_checklist.en.json
Labels: hackathon

#887 Add graph query for checking compliance of app service hosting plans
  checklists/appsvc_checklist.en.json
Labels: hackathon

#876 AZFW - DNS Proxy Graph
  checklists/alz_checklist.en.json
Labels: hackathon

#904 Added ARG query for A02.02 in servicebus_checklist.en.json".
  checklists/servicebus_checklist.en.json
Labels: hackathon

#918 Automatic translation of checklists/network_appdelivery_checklist.en.json
  checklists-ext/fullwaf_checklist.en.json
  checklists/checklist.en.master.json
  checklists/network_appdelivery_checklist.en.json
  checklists/network_appdelivery_checklist.es.json
  checklists/network_appdelivery_checklist.ja.json
  checklists/network_appdelivery_checklist.ko.json
  checklists/network_appdelivery_checklist.pt.json
  checklists/network_appdelivery_checklist.zh-Hant.json
  checklists/waf_checklist.en.json
  checklists/waf_checklist.es.json
  checklists/waf_checklist.ja.json
  checklists/waf_checklist.ko.json
  checklists/waf_checklist.pt.json
  checklists/waf_checklist.zh-Hant.json
  spreadsheet/macrofree/checklist.en.master.xlsx
  spreadsheet/macrofree/network_appdelivery_checklist.en.xlsx
  spreadsheet/macrofree/network_appdelivery_checklist.es.xlsx
  spreadsheet/macrofree/network_appdelivery_checklist.ja.xlsx
  spreadsheet/macrofree/network_appdelivery_checklist.ko.xlsx
  spreadsheet/macrofree/network_appdelivery_checklist.pt.xlsx
  spreadsheet/macrofree/network_appdelivery_checklist.zh-Hant.xlsx
  spreadsheet/macrofree/waf_checklist.en.xlsx
  spreadsheet/macrofree/waf_checklist.es.xlsx
  spreadsheet/macrofree/waf_checklist.ja.xlsx
  spreadsheet/macrofree/waf_checklist.ko.xlsx
  spreadsheet/macrofree/waf_checklist.pt.xlsx
  spreadsheet/macrofree/waf_checklist.zh-Hant.xlsx
  workbooks/alz_checklist.en_network_counters.json
  workbooks/alz_checklist.en_network_counters_template.json
  workbooks/alz_checklist.en_network_tabcounters.json
  workbooks/alz_checklist.en_network_tabcounters_template.json
  workbooks/alz_checklist.en_network_workbook.json
  workbooks/alz_checklist.en_network_workbook_template.json
  workbooks/appdelivery_checklist.en_network_counters_workbook.json
  workbooks/appdelivery_checklist.en_network_counters_workbook_template.json
  workbooks/appdelivery_checklist.en_network_workbook.json
  workbooks/appdelivery_checklist.en_network_workbook_template.json
  workbooks/network_appdelivery_checklist.en_counters_workbook.json
  workbooks/network_appdelivery_checklist.en_counters_workbook_template.json
  workbooks/network_appdelivery_checklist.en_workbook.json
  workbooks/network_appdelivery_checklist.en_workbook_template.json
Labels: automated

#898 Adding ARG (A01.01, A01.11, A01.18) to afd_checklist.en.json
  checklists/afd_checklist.en.json
Labels: hackathon

#892 Added comma to the end of ARG query line and also added compliant check to the ARG query - A01.38 in network_appdelivery_checklist.en.json
  checklists/network_appdelivery_checklist.en.json
Labels: hackathon

#920 Automatic translation of checklists/afd_checklist.en.json
  checklists-ext/fullwaf_checklist.en.json
  checklists/afd_checklist.en.json
  checklists/afd_checklist.es.json
  checklists/afd_checklist.ja.json
  checklists/afd_checklist.ko.json
  checklists/afd_checklist.pt.json
  checklists/afd_checklist.zh-Hant.json
  checklists/checklist.en.master.json
  checklists/waf_checklist.en.json
  checklists/waf_checklist.es.json
  checklists/waf_checklist.ja.json
  checklists/waf_checklist.ko.json
  checklists/waf_checklist.pt.json
  checklists/waf_checklist.zh-Hant.json
  spreadsheet/macrofree/afd_checklist.en.xlsx
  spreadsheet/macrofree/afd_checklist.es.xlsx
  spreadsheet/macrofree/afd_checklist.ja.xlsx
  spreadsheet/macrofree/afd_checklist.ko.xlsx
  spreadsheet/macrofree/afd_checklist.pt.xlsx
  spreadsheet/macrofree/afd_checklist.zh-Hant.xlsx
  spreadsheet/macrofree/checklist.en.master.xlsx
  spreadsheet/macrofree/waf_checklist.en.xlsx
  spreadsheet/macrofree/waf_checklist.es.xlsx
  spreadsheet/macrofree/waf_checklist.ja.xlsx
  spreadsheet/macrofree/waf_checklist.ko.xlsx
  spreadsheet/macrofree/waf_checklist.pt.xlsx
  spreadsheet/macrofree/waf_checklist.zh-Hant.xlsx
  workbooks/afd_checklist.en_counters_workbook.json
  workbooks/afd_checklist.en_counters_workbook_template.json
  workbooks/afd_checklist.en_workbook.json
  workbooks/afd_checklist.en_workbook_template.json
  workbooks/alz_checklist.en_network_counters.json
  workbooks/alz_checklist.en_network_counters_template.json
  workbooks/alz_checklist.en_network_tabcounters.json
  workbooks/alz_checklist.en_network_tabcounters_template.json
  workbooks/alz_checklist.en_network_workbook.json
  workbooks/alz_checklist.en_network_workbook_template.json
  workbooks/appdelivery_checklist.en_network_counters_workbook.json
  workbooks/appdelivery_checklist.en_network_counters_workbook_template.json
  workbooks/appdelivery_checklist.en_network_workbook.json
  workbooks/appdelivery_checklist.en_network_workbook_template.json
Labels: automated

#879 Added ARG query for 10.09 in alz_checklist.en.json
  checklists/alz_checklist.en.json
Labels: hackathon

#922 Automatic translation of checklists/alz_checklist.en.json
  checklists-ext/fullwaf_checklist.en.json
  checklists/alz_checklist.en.json
  checklists/alz_checklist.es.json
  checklists/alz_checklist.ja.json
  checklists/alz_checklist.ko.json
  checklists/alz_checklist.pt.json
  checklists/alz_checklist.zh-Hant.json
  checklists/checklist.en.master.json
  checklists/waf_checklist.en.json
  checklists/waf_checklist.es.json
  checklists/waf_checklist.ja.json
  checklists/waf_checklist.ko.json
  checklists/waf_checklist.pt.json
  checklists/waf_checklist.zh-Hant.json
  spreadsheet/macrofree/alz_checklist.en.xlsx
  spreadsheet/macrofree/alz_checklist.es.xlsx
  spreadsheet/macrofree/alz_checklist.ja.xlsx
  spreadsheet/macrofree/alz_checklist.ko.xlsx
  spreadsheet/macrofree/alz_checklist.pt.xlsx
  spreadsheet/macrofree/alz_checklist.zh-Hant.xlsx
  spreadsheet/macrofree/checklist.en.master.xlsx
  spreadsheet/macrofree/waf_checklist.en.xlsx
  spreadsheet/macrofree/waf_checklist.es.xlsx
  spreadsheet/macrofree/waf_checklist.ja.xlsx
  spreadsheet/macrofree/waf_checklist.ko.xlsx
  spreadsheet/macrofree/waf_checklist.pt.xlsx
  spreadsheet/macrofree/waf_checklist.zh-Hant.xlsx
  workbooks/alz_checklist.en_counters_workbook.json
  workbooks/alz_checklist.en_counters_workbook_template.json
  workbooks/alz_checklist.en_network_counters.json
  workbooks/alz_checklist.en_network_counters_template.json
  workbooks/alz_checklist.en_network_tabcounters.json
  workbooks/alz_checklist.en_network_tabcounters_template.json
  workbooks/alz_checklist.en_network_workbook.json
  workbooks/alz_checklist.en_network_workbook_template.json
  workbooks/alz_checklist.en_workbook.json
  workbooks/alz_checklist.en_workbook_template.json
  workbooks/appdelivery_checklist.en_network_counters_workbook.json
  workbooks/appdelivery_checklist.en_network_counters_workbook_template.json
  workbooks/appdelivery_checklist.en_network_workbook.json
  workbooks/appdelivery_checklist.en_network_workbook_template.json
Labels: automated

#873 Alisakina99 mandatorymfaplanning
  checklists/alz_checklist.en.json
Labels: landingzone

#923 Automatic translation of checklists/alz_checklist.en.json
  checklists-ext/fullwaf_checklist.en.json
  checklists/alz_checklist.en.json
  checklists/alz_checklist.es.json
  checklists/alz_checklist.ja.json
  checklists/alz_checklist.ko.json
  checklists/alz_checklist.pt.json
  checklists/alz_checklist.zh-Hant.json
  checklists/checklist.en.master.json
  checklists/waf_checklist.en.json
  checklists/waf_checklist.es.json
  checklists/waf_checklist.ja.json
  checklists/waf_checklist.ko.json
  checklists/waf_checklist.pt.json
  checklists/waf_checklist.zh-Hant.json
  spreadsheet/macrofree/alz_checklist.en.xlsx
  spreadsheet/macrofree/alz_checklist.es.xlsx
  spreadsheet/macrofree/alz_checklist.ja.xlsx
  spreadsheet/macrofree/alz_checklist.ko.xlsx
  spreadsheet/macrofree/alz_checklist.pt.xlsx
  spreadsheet/macrofree/alz_checklist.zh-Hant.xlsx
  spreadsheet/macrofree/checklist.en.master.xlsx
  spreadsheet/macrofree/waf_checklist.en.xlsx
  spreadsheet/macrofree/waf_checklist.es.xlsx
  spreadsheet/macrofree/waf_checklist.ja.xlsx
  spreadsheet/macrofree/waf_checklist.ko.xlsx
  spreadsheet/macrofree/waf_checklist.pt.xlsx
  spreadsheet/macrofree/waf_checklist.zh-Hant.xlsx
  workbooks/alz_checklist.en_counters_workbook.json
  workbooks/alz_checklist.en_counters_workbook_template.json
  workbooks/alz_checklist.en_network_counters.json
  workbooks/alz_checklist.en_network_counters_template.json
  workbooks/alz_checklist.en_network_tabcounters.json
  workbooks/alz_checklist.en_network_tabcounters_template.json
  workbooks/alz_checklist.en_network_workbook.json
  workbooks/alz_checklist.en_network_workbook_template.json
  workbooks/alz_checklist.en_workbook.json
  workbooks/alz_checklist.en_workbook_template.json
  workbooks/appdelivery_checklist.en_network_counters_workbook.json
  workbooks/appdelivery_checklist.en_network_counters_workbook_template.json
  workbooks/appdelivery_checklist.en_network_workbook.json
  workbooks/appdelivery_checklist.en_network_workbook_template.json
Labels: automated
