Repository Azure/review-checklists, pull requests merged in 2024-10, with the labels that each got.

#937 Latest version of the WAF service guides retrieved
  checklists-ext/appservicewebapps_sg_checklist.en.json
  checklists-ext/azureapplicationgateway_sg_checklist.en.json
  checklists-ext/azureblobstorage_sg_checklist.en.json
  checklists-ext/azureexpressroute_sg_checklist.en.json
  checklists-ext/azurefiles_sg_checklist.en.json
  checklists-ext/azurefirewall_sg_checklist.en.json
  checklists-ext/azurefrontdoor_sg_checklist.en.json
  checklists-ext/azurekubernetesservice_sg_checklist.en.json
  checklists-ext/azuremachinelearning_sg_checklist.en.json
  checklists-ext/azureopenai_sg_checklist.en.json
  checklists-ext/virtualmachines_sg_checklist.en.json
  checklists-ext/wafsg_checklist.en.json
Labels: automated

#938 Naigaras sap6 arg
  checklists/sap_checklist.en.json
Labels: hackathon

#946 Automatic translation of checklists/sap_checklist.en.json
  checklists-ext/fullwaf_checklist.en.json
  checklists/checklist.en.master.json
  checklists/sap_checklist.en.json
  checklists/sap_checklist.es.json
  checklists/sap_checklist.ja.json
  checklists/sap_checklist.ko.json
  checklists/sap_checklist.pt.json
  checklists/sap_checklist.zh-Hant.json
  checklists/waf_checklist.en.json
  checklists/waf_checklist.es.json
  checklists/waf_checklist.ja.json
  checklists/waf_checklist.ko.json
  checklists/waf_checklist.pt.json
  checklists/waf_checklist.zh-Hant.json
  spreadsheet/macrofree/checklist.en.master.xlsx
  spreadsheet/macrofree/sap_checklist.en.xlsx
  spreadsheet/macrofree/sap_checklist.es.xlsx
  spreadsheet/macrofree/sap_checklist.ja.xlsx
  spreadsheet/macrofree/sap_checklist.ko.xlsx
  spreadsheet/macrofree/sap_checklist.pt.xlsx
  spreadsheet/macrofree/sap_checklist.zh-Hant.xlsx
  spreadsheet/macrofree/waf_checklist.en.xlsx
  spreadsheet/macrofree/waf_checklist.es.xlsx
  spreadsheet/macrofree/waf_checklist.ja.xlsx
  spreadsheet/macrofree/waf_checklist.ko.xlsx
  spreadsheet/macrofree/waf_checklist.pt.xlsx
  spreadsheet/macrofree/waf_checklist.zh-Hant.xlsx
  workbooks/alz_checklist.en_network_counters.json
  workbooks/alz_checklist.en_network_counters_template.json
  workbooks/alz_checklist.en_network_tabcounters.json
  workbooks/alz_checklist.en_network_tabcounters_template.json
  workbooks/alz_checklist.en_network_workbook.json
  workbooks/alz_checklist.en_network_workbook_template.json
  workbooks/appdelivery_checklist.en_network_counters_workbook.json
  workbooks/appdelivery_checklist.en_network_counters_workbook_template.json
  workbooks/appdelivery_checklist.en_network_workbook.json
  workbooks/appdelivery_checklist.en_network_workbook_template.json
  workbooks/sap_checklist.en_counters_workbook.json
  workbooks/sap_checklist.en_counters_workbook_template.json
  workbooks/sap_checklist.en_workbook.json
  workbooks/sap_checklist.en_workbook_template.json
Labels: automated

#948 Latest version of the WAF service guides retrieved
  checklists-ext/appservicewebapps_sg_checklist.en.json
  checklists-ext/azureapplicationgateway_sg_checklist.en.json
  checklists-ext/azureblobstorage_sg_checklist.en.json
  checklists-ext/azureexpressroute_sg_checklist.en.json
  checklists-ext/azurefiles_sg_checklist.en.json
  checklists-ext/azurefirewall_sg_checklist.en.json
  checklists-ext/azurefrontdoor_sg_checklist.en.json
  checklists-ext/azurekubernetesservice_sg_checklist.en.json
  checklists-ext/azuremachinelearning_sg_checklist.en.json
  checklists-ext/azureopenai_sg_checklist.en.json
  checklists-ext/virtualmachines_sg_checklist.en.json
  checklists-ext/wafsg_checklist.en.json
Labels: automated

#883 Added the right documentation (learn more link) to A01.08 in network_appdelivery_checklist.en.json
  checklists/network_appdelivery_checklist.en.json
Labels: hackathon

#866 adjust severity for e960fc6b-4ab2-4db6-9609-3745135f9ffa
  checklists/alz_checklist.en.json
  checklists/alz_checklist.es.json
  checklists/alz_checklist.ja.json
  checklists/alz_checklist.ko.json
  checklists/alz_checklist.pt.json
  checklists/alz_checklist.zh-Hant.json
  spreadsheet/review_checklist.xlsm
Labels: landingzone

#902 Added ARG query for AOAI.12, AOAI.32, AOAI.38, AOAI.47, AOAI.50, AOAI.54, AOAI.57, AOAI.82 and removed duplicate item AOAI.67 in aoai_checklist.en.json
  checklists/aoai_checklist.en.json
Labels: hackathon

#889 Added ARG query for "Define a strategy for extension updates" in azure_arc_checklist.en.json
  checklists/azure_arc_checklist.en.json
Labels: hackathon

#885 Added ARG query to A01.54 in network_appdelivery_checklist.en.json
  checklists/network_appdelivery_checklist.en.json
Labels: hackathon

#951 Latest version of the WAF service guides retrieved
  checklists-ext/appservicewebapps_sg_checklist.en.json
  checklists-ext/azureapplicationgateway_sg_checklist.en.json
  checklists-ext/azureblobstorage_sg_checklist.en.json
  checklists-ext/azureexpressroute_sg_checklist.en.json
  checklists-ext/azurefiles_sg_checklist.en.json
  checklists-ext/azurefirewall_sg_checklist.en.json
  checklists-ext/azurefrontdoor_sg_checklist.en.json
  checklists-ext/azurekubernetesservice_sg_checklist.en.json
  checklists-ext/azuremachinelearning_sg_checklist.en.json
  checklists-ext/azureopenai_sg_checklist.en.json
  checklists-ext/virtualmachines_sg_checklist.en.json
  checklists-ext/wafsg_checklist.en.json
Labels: automated

#954 Latest version of the WAF service guides retrieved
  checklists-ext/appservicewebapps_sg_checklist.en.json
  checklists-ext/azureapplicationgateway_sg_checklist.en.json
  checklists-ext/azureblobstorage_sg_checklist.en.json
  checklists-ext/azureexpressroute_sg_checklist.en.json
  checklists-ext/azurefiles_sg_checklist.en.json
  checklists-ext/azurefirewall_sg_checklist.en.json
  checklists-ext/azurefrontdoor_sg_checklist.en.json
  checklists-ext/azurekubernetesservice_sg_checklist.en.json
  checklists-ext/azuremachinelearning_sg_checklist.en.json
  checklists-ext/azureopenai_sg_checklist.en.json
  checklists-ext/virtualmachines_sg_checklist.en.json
  checklists-ext/wafsg_checklist.en.json
Labels: automated

#893 Added ARG query for "Use Azure Arc-enabled servers to control software updates deployments to servers" in azure_arc_checklist.en.json
  checklists/azure_arc_checklist.en.json
Labels: hackathon

#955 Automatic translation of checklists/datasecurity_checklist.en.json
  checklists-ext/fullwaf_checklist.en.json
  checklists/checklist.en.master.json
  checklists/datasecurity_checklist.en.json
  checklists/datasecurity_checklist.es.json
  checklists/datasecurity_checklist.ja.json
  checklists/datasecurity_checklist.ko.json
  checklists/datasecurity_checklist.pt.json
  checklists/datasecurity_checklist.zh-Hant.json
  checklists/waf_checklist.en.json
  checklists/waf_checklist.es.json
  checklists/waf_checklist.ja.json
  checklists/waf_checklist.ko.json
  checklists/waf_checklist.pt.json
  checklists/waf_checklist.zh-Hant.json
  spreadsheet/macrofree/checklist.en.master.xlsx
  spreadsheet/macrofree/datasecurity_checklist.en.xlsx
  spreadsheet/macrofree/datasecurity_checklist.es.xlsx
  spreadsheet/macrofree/datasecurity_checklist.ja.xlsx
  spreadsheet/macrofree/datasecurity_checklist.ko.xlsx
  spreadsheet/macrofree/datasecurity_checklist.pt.xlsx
  spreadsheet/macrofree/datasecurity_checklist.zh-Hant.xlsx
  spreadsheet/macrofree/waf_checklist.en.xlsx
  spreadsheet/macrofree/waf_checklist.es.xlsx
  spreadsheet/macrofree/waf_checklist.ja.xlsx
  spreadsheet/macrofree/waf_checklist.ko.xlsx
  spreadsheet/macrofree/waf_checklist.pt.xlsx
  spreadsheet/macrofree/waf_checklist.zh-Hant.xlsx
  workbooks/alz_checklist.en_network_counters.json
  workbooks/alz_checklist.en_network_counters_template.json
  workbooks/alz_checklist.en_network_tabcounters.json
  workbooks/alz_checklist.en_network_tabcounters_template.json
  workbooks/alz_checklist.en_network_workbook.json
  workbooks/alz_checklist.en_network_workbook_template.json
  workbooks/appdelivery_checklist.en_network_counters_workbook.json
  workbooks/appdelivery_checklist.en_network_counters_workbook_template.json
  workbooks/appdelivery_checklist.en_network_workbook.json
  workbooks/appdelivery_checklist.en_network_workbook_template.json
Labels: automated

#957 Automatic translation of checklists/databricks_checklist.en.json
  checklists-ext/fullwaf_checklist.en.json
  checklists/checklist.en.master.json
  checklists/databricks_checklist.en.json
  checklists/databricks_checklist.es.json
  checklists/databricks_checklist.ja.json
  checklists/databricks_checklist.ko.json
  checklists/databricks_checklist.pt.json
  checklists/databricks_checklist.zh-Hant.json
  checklists/waf_checklist.en.json
  checklists/waf_checklist.es.json
  checklists/waf_checklist.ja.json
  checklists/waf_checklist.ko.json
  checklists/waf_checklist.pt.json
  checklists/waf_checklist.zh-Hant.json
  spreadsheet/macrofree/checklist.en.master.xlsx
  spreadsheet/macrofree/databricks_checklist.en.xlsx
  spreadsheet/macrofree/databricks_checklist.es.xlsx
  spreadsheet/macrofree/databricks_checklist.ja.xlsx
  spreadsheet/macrofree/databricks_checklist.ko.xlsx
  spreadsheet/macrofree/databricks_checklist.pt.xlsx
  spreadsheet/macrofree/databricks_checklist.zh-Hant.xlsx
  spreadsheet/macrofree/waf_checklist.en.xlsx
  spreadsheet/macrofree/waf_checklist.es.xlsx
  spreadsheet/macrofree/waf_checklist.ja.xlsx
  spreadsheet/macrofree/waf_checklist.ko.xlsx
  spreadsheet/macrofree/waf_checklist.pt.xlsx
  spreadsheet/macrofree/waf_checklist.zh-Hant.xlsx
  workbooks/alz_checklist.en_network_counters.json
  workbooks/alz_checklist.en_network_counters_template.json
  workbooks/alz_checklist.en_network_tabcounters.json
  workbooks/alz_checklist.en_network_tabcounters_template.json
  workbooks/alz_checklist.en_network_workbook.json
  workbooks/alz_checklist.en_network_workbook_template.json
  workbooks/appdelivery_checklist.en_network_counters_workbook.json
  workbooks/appdelivery_checklist.en_network_counters_workbook_template.json
  workbooks/appdelivery_checklist.en_network_workbook.json
  workbooks/appdelivery_checklist.en_network_workbook_template.json
Labels: automated

#915 Updated eh_checklist.en.json - A01.01, A01.02, B01.2, B01.3
  checklists/eh_checklist.en.json
Labels: hackathon

#890 Added ARG query for "Design a monitoring strategy to send metrics and logs to an Log Analytics workspace" in azure_arc_checklist.en.json
  checklists/azure_arc_checklist.en.json
Labels: hackathon

#884 Added ARG query for A01.40 in network_appdelivery_checklist.en.json
  checklists/network_appdelivery_checklist.en.json
Labels: hackathon

#959 Automatic translation of checklists/azure_arc_checklist.en.json
  checklists-ext/fullwaf_checklist.en.json
  checklists/azure_arc_checklist.en.json
  checklists/azure_arc_checklist.es.json
  checklists/azure_arc_checklist.ja.json
  checklists/azure_arc_checklist.ko.json
  checklists/azure_arc_checklist.pt.json
  checklists/azure_arc_checklist.zh-Hant.json
  checklists/checklist.en.master.json
  checklists/waf_checklist.en.json
  spreadsheet/macrofree/azure_arc_checklist.en.xlsx
  spreadsheet/macrofree/azure_arc_checklist.es.xlsx
  spreadsheet/macrofree/azure_arc_checklist.ja.xlsx
  spreadsheet/macrofree/azure_arc_checklist.ko.xlsx
  spreadsheet/macrofree/azure_arc_checklist.pt.xlsx
  spreadsheet/macrofree/azure_arc_checklist.zh-Hant.xlsx
  spreadsheet/macrofree/checklist.en.master.xlsx
  spreadsheet/macrofree/waf_checklist.en.xlsx
  spreadsheet/macrofree/waf_checklist.es.xlsx
  spreadsheet/macrofree/waf_checklist.ja.xlsx
  spreadsheet/macrofree/waf_checklist.ko.xlsx
  spreadsheet/macrofree/waf_checklist.pt.xlsx
  spreadsheet/macrofree/waf_checklist.zh-Hant.xlsx
  workbooks/alz_checklist.en_network_counters.json
  workbooks/alz_checklist.en_network_counters_template.json
  workbooks/alz_checklist.en_network_tabcounters.json
  workbooks/alz_checklist.en_network_tabcounters_template.json
  workbooks/alz_checklist.en_network_workbook.json
  workbooks/alz_checklist.en_network_workbook_template.json
  workbooks/appdelivery_checklist.en_network_counters_workbook.json
  workbooks/appdelivery_checklist.en_network_counters_workbook_template.json
  workbooks/appdelivery_checklist.en_network_workbook.json
  workbooks/appdelivery_checklist.en_network_workbook_template.json
  workbooks/azure_arc_checklist.en_counters_workbook.json
  workbooks/azure_arc_checklist.en_counters_workbook_template.json
  workbooks/azure_arc_checklist.en_workbook.json
  workbooks/azure_arc_checklist.en_workbook_template.json
Labels: automated

#961 Automatic translation of checklists/alz_checklist.en.json
  checklists-ext/fullwaf_checklist.en.json
  checklists/alz_checklist.en.json
  checklists/alz_checklist.es.json
  checklists/alz_checklist.ja.json
  checklists/alz_checklist.ko.json
  checklists/alz_checklist.pt.json
  checklists/alz_checklist.zh-Hant.json
  checklists/checklist.en.master.json
  checklists/waf_checklist.en.json
  checklists/waf_checklist.es.json
  checklists/waf_checklist.ja.json
  checklists/waf_checklist.ko.json
  checklists/waf_checklist.pt.json
  checklists/waf_checklist.zh-Hant.json
  spreadsheet/macrofree/alz_checklist.en.xlsx
  spreadsheet/macrofree/alz_checklist.es.xlsx
  spreadsheet/macrofree/alz_checklist.ja.xlsx
  spreadsheet/macrofree/alz_checklist.ko.xlsx
  spreadsheet/macrofree/alz_checklist.pt.xlsx
  spreadsheet/macrofree/alz_checklist.zh-Hant.xlsx
  spreadsheet/macrofree/checklist.en.master.xlsx
  spreadsheet/macrofree/waf_checklist.en.xlsx
  spreadsheet/macrofree/waf_checklist.es.xlsx
  spreadsheet/macrofree/waf_checklist.ja.xlsx
  spreadsheet/macrofree/waf_checklist.ko.xlsx
  spreadsheet/macrofree/waf_checklist.pt.xlsx
  spreadsheet/macrofree/waf_checklist.zh-Hant.xlsx
  workbooks/alz_checklist.en_counters_workbook.json
  workbooks/alz_checklist.en_counters_workbook_template.json
  workbooks/alz_checklist.en_network_counters.json
  workbooks/alz_checklist.en_network_counters_template.json
  workbooks/alz_checklist.en_network_tabcounters.json
  workbooks/alz_checklist.en_network_tabcounters_template.json
  workbooks/alz_checklist.en_network_workbook.json
  workbooks/alz_checklist.en_network_workbook_template.json
  workbooks/alz_checklist.en_workbook.json
  workbooks/alz_checklist.en_workbook_template.json
  workbooks/appdelivery_checklist.en_network_counters_workbook.json
  workbooks/appdelivery_checklist.en_network_counters_workbook_template.json
  workbooks/appdelivery_checklist.en_network_workbook.json
  workbooks/appdelivery_checklist.en_network_workbook_template.json
Labels: automated

#965 Removing duplicate or very similar checks and performing consolidation
  checklists/alz_checklist.en.json
Labels: landingzone

#966 Automatic translation of checklists/alz_checklist.en.json
  checklists-ext/fullwaf_checklist.en.json
  checklists/alz_checklist.en.json
  checklists/checklist.en.master.json
  checklists/waf_checklist.en.json
  checklists/waf_checklist.es.json
  checklists/waf_checklist.ja.json
  checklists/waf_checklist.ko.json
  checklists/waf_checklist.pt.json
  checklists/waf_checklist.zh-Hant.json
  spreadsheet/macrofree/alz_checklist.en.xlsx
  spreadsheet/macrofree/alz_checklist.es.xlsx
  spreadsheet/macrofree/alz_checklist.ja.xlsx
  spreadsheet/macrofree/alz_checklist.ko.xlsx
  spreadsheet/macrofree/alz_checklist.pt.xlsx
  spreadsheet/macrofree/alz_checklist.zh-Hant.xlsx
  spreadsheet/macrofree/checklist.en.master.xlsx
  spreadsheet/macrofree/waf_checklist.en.xlsx
  spreadsheet/macrofree/waf_checklist.es.xlsx
  spreadsheet/macrofree/waf_checklist.ja.xlsx
  spreadsheet/macrofree/waf_checklist.ko.xlsx
  spreadsheet/macrofree/waf_checklist.pt.xlsx
  spreadsheet/macrofree/waf_checklist.zh-Hant.xlsx
  workbooks/alz_checklist.en_counters_workbook.json
  workbooks/alz_checklist.en_counters_workbook_template.json
  workbooks/alz_checklist.en_network_counters.json
  workbooks/alz_checklist.en_network_counters_template.json
  workbooks/alz_checklist.en_network_tabcounters.json
  workbooks/alz_checklist.en_network_tabcounters_template.json
  workbooks/alz_checklist.en_network_workbook.json
  workbooks/alz_checklist.en_network_workbook_template.json
  workbooks/alz_checklist.en_workbook.json
  workbooks/alz_checklist.en_workbook_template.json
  workbooks/appdelivery_checklist.en_network_counters_workbook.json
  workbooks/appdelivery_checklist.en_network_counters_workbook_template.json
  workbooks/appdelivery_checklist.en_network_workbook.json
  workbooks/appdelivery_checklist.en_network_workbook_template.json
Labels: automated
